#[en]
#    languageName = "English"
#    contentDir = "content/en"
#   weight = 1
#    [en.params.head]
#        tagline = "A Hugo Theme"
#    [en.params.social]
#        title = "Follow me"
#        caption = "I work on everything coding and tweet developer memes"
#    [en.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."

[ru]
    languageName = "Русский"
    contentDir = "content"
    weight = 1
    [ru.params.head]
        tagline = "A Hugo Theme"
    [ru.params.sections.blog]
        title = "Блог"
        sort = "date"
        reverse = true
      #  cols = 3
       # color = "body-tertiary"
       # padding = "0"
       # orientation = "stacked"
       # style = "border-0 card-zoom card-body-margin"
        reference = "Больше..."    
    [ru.params.social]
        title = "Follow me"
        caption = "I work on everything coding and tweet developer memes"
    [ru.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."