[[main]]
  name = "Главная"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Тэги"
  pageRef = "/tags"
  weight = 30
  
[[main]]
  name = "Блог"
  pageRef = "/blog"
  weight = 20  

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Блог"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Проекты"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Простой проект"
  pageRef = "/projects/sample-project/"
  parent = "Проекты"
  weight = 1

[[sample]]
  name = "Другой проект"
  pageRef = "/projects/another-project/"
  parent = "Проекты"
  weight = 2
# toml-docs-end sample-navigation